apiVersion: apps/v1
kind: Deployment
metadata:
  name: kedge-deployment
  labels:
    app: kedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kedge
  template:
    metadata:
      labels:
        app: kedge
    spec:
      containers:
      - name: kedge
        image: stdengacrrnd.azurecr.io/kedge:preview1
        volumeMounts:
        - name: sys-fs-cgroup
          mountPath: /sys/fs/cgroup
        - name: var-lib-docker
          mountPath: /var/lib/docker
        securityContext:
          privileged: true
      volumes:
      - name: sys-fs-cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: var-lib-docker
        emptyDir: {}
      imagePullSecrets:
      - name: regcred